### ISSUE TITLE
SQL queries with hardcoded database name

### ISSUE THREAD

**Issue by carloslucenah** [telefonicaid/fiware-facts#70]
The database name is hardcoded in SQL queries. Won't work unless the database name would be "cloto".

**Comment by flopezag** [comment]
It is a configurable parameter that can be found in [https://github.com/telefonicaid/fiware-facts/blob/develop/facts_conf/fiware-facts.cfg#L40]. Do you tried to change it? Nevertheless keep in mind that the DB should be the same that we have in the cloto component.

**Comment by carloslucenah** [comment]
Yes, tested and it triggers an error because the user has not permissions over database "cloto". See https://github.com/telefonicaid/fiware-cloto/issues/74.

**Comment by flopezag** [comment]
It has been resolved in [https://github.com/telefonicaid/fiware-facts/pull/77]
